# base
spring: 
  datasource: 
    jejupass: 
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mariadb://34.64.232.46:3306/jejupass-db?characterEncoding=utf-8&serverTimezone=UTC 
      username: root
      password: dudwndkfma1@
      
  servlet: 
    multipart: 
      enabled: true 
      maxFileSize: 1000MB
      maxRequestSize: 1000MB

# introPage
  webservice:
    intro: index.do

# file
file:
  upload:
    #upload path (local path)
    path: C:/jejupass/upfile 
    #upload url
    url: /upfile   
    
# filght 
filght:
    url: http://openapi.airport.co.kr/service/rest/FlightScheduleList/getDflightScheduleList
    serviceKey: wDQJwlk1Qy8oK2FqYEhgeT0225VKyPbLDpmjvF%2Baq4AibwUukAvI%2BtRAZFK57XHTWMGaoAyzTvenuwNYn8VvqQ%3D%3D