# base
spring: 
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/jejupass?serverTimezone=Asia/Seoul
      username: root
      password: dudwn12#$
      
  servlet: 
    multipart: 
      enabled: true 
      maxFileSize: 1000MB
      maxRequestSize: 1000MB

# introPage
  webservice:
    intro: index.do

# file
file:
  upload:
    #upload path (local path)
    path: C:/jejupass/upfile 
    #upload url
    url: /upfile   
    
# filght 
filght:
    url: http://openapi.airport.co.kr/service/rest/FlightScheduleList/getDflightScheduleList
    serviceKey: wDQJwlk1Qy8oK2FqYEhgeT0225VKyPbLDpmjvF%2Baq4AibwUukAvI%2BtRAZFK57XHTWMGaoAyzTvenuwNYn8VvqQ%3D%3D